# backend/Dockerfile
FROM node:20

WORKDIR /app

# Copy package.json and package-lock.json first (leverage cache)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

EXPOSE 4000

CMD ["npm", "run", "dev"]