// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';


const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Show a clear error in the browser and console
  const message =
    'Supabase environment variables are missing or invalid.\n' +
    'Check VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your environment.';
  if (typeof window !== 'undefined') {
    document.body.innerHTML = `<div style="color:red;font-size:1.5rem;padding:2rem;text-align:center;">${message.replace(/\n/g,'<br>')}</div>`;
  }
  throw new Error(message);
}



export  const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
console.log("URL:", SUPABASE_URL);
console.log("KEY:", SUPABASE_PUBLISHABLE_KEY);

